version: '3'
services:
  jupyter:
    # image: gpu-conda-jupyter:leo
    image: gpu-conda-jupyter:latest
    # image: tensorflow/tensorflow:2.15.0-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "${USERID}8:8888"
      - "${USERID}6:8866"
    user: root
    shm_size: 256G
    volumes:
      - ${HOME}/jupyter:/jupyter
      - ${HOME}/jupyter/.jupyter:/root/.jupyter
      - ./demo:/demo
      - /data:/data
      - ./scripts:/scripts
      # - ${HOME}/docker:/docker
    working_dir: /jupyter
    restart: unless-stopped
    command: sleep infinity
    # command: bash -c /scripts/run.sh
