version: '2.4'
services:
  jupyter:
    image: tensorflow/tensorflow:2.0.0b0-gpu-py3-jupyter
    ports:
      - 8088:8888
    user: root
    ipc: host
    shm_size: 64G
    runtime: nvidia
    volumes:
      - ${HOME}/notebooks:/tf/notebooks
      - ./scripts:/tf/scripts
      - ./demo:/tf/demo
    command: sleep infinity
