version: '3'
services:
  jupyter:
    image: tensorflow/tensorflow:latest-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "${USERID}8:8888"
      - "${USERID}6:8866"
    user: root
    shm_size: 256G
    volumes:
      - ${HOME}/notebooks:/tf/notebooks
      - ./scripts:/tf/scripts
      - ./demo:/tf/demo
      - ./readme.md:/tf/readme.md
    working_dir: /tf
    command: sleep infinity
