version: '2.4'
services:
  jupyter:
    image: tensorflow/tensorflow:latest-gpu # cuda-10.2 image id: 8a8486aa1902
    ports:
      - 8088:8888
    user: root
    ipc: host
    shm_size: 64G
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    volumes:
      - ${HOME}/notebooks:/tf/notebooks
      - ./scripts:/tf/scripts
      - ./demo:/tf/demo
    command: sleep infinity
